kind: ConfigMap
apiVersion: v1
metadata:
  name: blue-config
  namespace: default
data:
  index.html: |
    <html>
        <head>
            <title>Blue</title>
        </head>
        <body>
            <h1 style="color: blue">Blue</h1>
        </body>
    </html>