stages:
  - build
  - push

Build:
  image: docker:latest
  stage: build
  services:
    - docker:dind
  tags:
    - docker
  before_script:
    - docker login -u "$CI_REGISTRY_USER" -p $CI_REGISTRY_PASSWORD
  script:
    - cd microservices/auth
    - docker build -t $CI_REGISTRY_USER/weatherapp-auth . --no-cache
    - cd ../UI
    - docker build -t $CI_REGISTRY_USER/weatherapp-ui .
    - docker ../weather
    - docker build -t $CI_REGISTRY_USER/weatherapp-weather .
  rules:
    - if: $CI_COMMIT_TAG == "null"
push:
  image: docker:latest
  stage: push
  tags:
    - docker
  services:
    - docker:dind
  before_script:
    - docker login -u "$CI_REGISTRY_USER" -p $CI_REGISTRY_PASSWORD
  script:
    - cd microservices/auth
    - docker build -t $CI_REGISTRY_USER/weatherapp-auth:$CI_COMMIT_SHA . --no-cache
    - docker push $CI_REGISTRY_USER/weatherapp-auth:$CI_COMMIT_SHA
    - docker ../UI
    - docker build -t $CI_REGISTRY_USER/weatherapp-ui:$CI_COMMIT_SHA .
    - docker push $CI_REGISTRY_USER/weatherapp-ui:$CI_COMMIT_SHA
    - cd ../weather
    - docker build -t $CI_REGISTRY_USER/weatherapp-weather:$CI_COMMIT_SHA .
    - docker push $CI_REGISTRY_USER/weatherapp-weather:$CI_COMMIT_SHA
  only:
    - main
  

  
  

