apiVersion: kudo.dev/v1beta1
parameters:
  - name: replicas
    description: Number of replicas that should be run as part of the deployment
    default: 2
    trigger: deploy
  - name: logFile
    description: The name of the Nginx access log file
    default: nginx-dev.log
    trigger: deploy
